language: python
python:
    - 3.6
    - 3.7
    - 3.8
before_install:
    - python --version
    - pip install -U pip
    - pip install -U pytest
    - pip install codecov
install:
    - pip install Cython
    - pip install -r requirements.txt
    - pip install ".[test]" .
script: pytest
after_success:
    - codecov
# deploy:
#     provider: pypi
#     username: "__token__"
#     password: 
#         secure: 
#     on:
#         tags: true
#         python: 3.8
